format_version: 10
pipelines:
  grafana-ansible: 
    group: terraform-group
    materials:
      mygit: 
        git: https://github.com/lalithvoop/tools-automation-code.git
        auto-update: true
        branch: main
    stages:
      - Create-vm:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            terraform-apply:
              tasks:
                - exec: {command: ansible-playbook, arguments: ["-i","grafana-private.vsldo.online,","-e","ansible_user=ec2-user","-e","ansible_password=DevOps321","-e","tool_name=grafana","tools.yml"], run_if: passed}