- name: set prompt for ec2
  ansible.builtin.shell: set-prompt prometheus 

- name: download and unarchive
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.51.0/prometheus-2.51.0.linux-amd64.tar.gz
    dest: /opt/
    remote_src: yes
    owner: bin
  
- name: adding prometheus.yml file in /opt/
  ansible.builtin.template:
    src: prometheus.yml
    desc: /opt/prometheus-2.51.0.linux-amd64/prometheus.yml

- name: Copy Prometheus Service File
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: Start Prometheus Service
  ansible.builtin.systemd_service:
    name: prometheus
    state: restarted
    enabled: yes
    daemon-reload: yes